sftp_host: s-6f8262c824f94eeea.server.transfer.eu-west-1.amazonaws.com
sftp_user: global-fishing-watch-nmea
sftp_pass_path: .secrets/sftp-password
sftp_pass_env: KPLER_SFTP_PASSWORD
sftp_directory: /global-fishing-watch-nmea
sftp_filename_format: "ais-%Y-%m-%d-%H-%M.nmea"
datetime_from: "2026-05-11T20:00"
datetime_to: "2026-05-11T20:10"
source_name: kpler
gcs_path: gs://scratch-tomas-ttl30d/kpler-sftp/
gcs_record_size: 20
chunk_size: 12500
concurrency: 20